function [x]=import_data()
%this function imports the bbc dataset

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/danny/Downloads/bbc/bbc.mtx
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/01/09 11:59:09

%% Initialize variables.
filename = '//DISKSTATION/Danny/Documents/Studie/CN/Text mining/bbc.mtx';
delimiter = ' ';
startRow = 3;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
bbc = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
for i=1:size(unique(bbc(:,2)),1)
    data{i}=bbc(bbc(:,2)==i,1:2:3);
end

for i=1:size(unique(bbc(:,2)),1)

y= zeros(1,9635);
y(data{i}(:,1))=data{i}(:,2);
x(i,:)=y;
end